### ISSUE TITLE
Set environment

### ISSUE THREAD

**Issue by maxwellmax** [newrelic/newrelic-monolog-logenricher-php#18]
## Summary

Create function for set environment of application.
example: setApplicationEnv

**Comment by kneitinger** [comment]
Hi @maxwellmax!

Could you elaborate on what you mean? I'm happy to discuss if this is something we would consider, but some use-case context, and perhaps an example code snippet would be really helpful in determining that.

Thanks!

**Comment by kneitinger** [comment]
Closing for now, please feel free to comment and we can re-open it if appropriate!
