### ISSUE TITLE
Monolog dependency is incorrect

### ISSUE THREAD

**Issue by billygilbert** [newrelic/newrelic-monolog-logenricher-php#21]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
NewRelic\Monolog\Enricher implements the Monolog ProcessorInterface yet that was not introduced until version 1.24.0 of Monolog

## Steps to Reproduce
composer require  "newrelic/monolog-enricher": "^1.0"
On a project that includes version 1.23.0 or older of Monolog

## Expected Behaviour
Composer would fail due to an unresolvable set of packages

## Relevant Logs / Code Samples
https://github.com/newrelic/newrelic-monolog-logenricher-php/blob/master/src/Processor.php#L16
https://github.com/Seldaek/monolog/commit/db8130ce83e4754708d6a4f5af06dd226aa01f4d

## Your Environment
```sh
PHP 7.1.33-16+0~20200514.38+debian10~1.gbp1e5820 (cli) (built: May 14 2020 13:41:21) ( NTS )

monolog/monolog                               1.16.0                     Sends your logs to files, sockets, inboxes, databases and various web services
newrelic/monolog-enricher                     1.0.0                      Monolog components to enable New Relic Logs

Linux DESKTOP-QTD0K0G 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 GNU/Linux
```

**Comment by kneitinger** [comment]
Thank you so much for bringing this to our attention @billygilbert, it is very appreciated

We merged in a fix that addresses this, please do not hesitate to reach out if there is any issue and we'll happily address with urgency!
