### ISSUE TITLE
support for monolog v3

### ISSUE THREAD

**Issue by RobVanAert** [newrelic/newrelic-monolog-logenricher-php#49]
## Summary

Create a new version that supports monolog/monolog version 3. Currently a framework like laravel could not be upgraded to version 10 cause that needs monolog version 3 and the current vesrion of newrelic-monolog-logenricher does not allow this.

**Comment by moffe42** [comment]
An initial attempt at porting to use Monolog 3. Feedback is much appreciated

**Comment by aat2703** [comment]
@mfulb any news on this?

**Comment by lavarou** [comment]
@moffe42 @aat2703 Thank you for your interest in this New Relic product offering. However, the New Relic PHP agent (version 10.3.0 and newer) supports Monolog 2 and Monolog 3 automatic log forwarding. This is the recommended way to capture log output from your PHP application. [Learn more about automatic log forwarding](https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-php/#automatic-logs-in-context).

**Comment by aat2703** [comment]
Im sorry to hear this. There is some problems with automatic log forwarding. When using AWS Lambda with Docker the containers could be killed before sending log data to New Relic. Also if not enough log data is being generated the daemon will not send the data to New Relic.

**Comment by aat2703** [comment]
The resources you're refering to is our exact configuration. Still sometimes when a container is only being invoked once the data never arrives in New Relic. This is often the case of background jobs handled by AWS Lambda with Docker. 

I'll have to say again. I'm really disappointed with New Relic archiving this repository. And all we're left with is a Daemon that does not work as expected.
